### ISSUE TITLE
Syntax goes away for ES6

### ISSUE THREAD

**Issue by jefflam** [crisward/sublime-tag#1]
Hello! 

First off, thank you very much for creating this syntax for Riot Tags. Have been looking for one as I'm trying out Riotjs.

I do have an issue which I hope you can help fix though. 

Right now the syntax highlighting works, even for ES6, using your syntax highlighter. However, as RiotJS requires a type on the <script> tag to include 'type="es6", the syntax highlighting breaks.

Is there a way you can fix the syntax highlighter to also accept the script tag with type='es6'? I.e. <script type="es6"> for syntax highlighting?

Thanks!

**Comment by jefflam** [comment]
Ok I just tested and it seems like removing the type="es6" doesn't really affect the Riot compiler. Seems like it is just more of a decorative function than anything else to display the type. Will close the issue!

**Comment by crisward** [comment]
Thanks...
