### ISSUE TITLE
Syntax highlighting always defaults to Riot (Jade), but I would like it to default to Riot Tag

### ISSUE THREAD

**Issue by mmanneva** [crisward/sublime-tag#3]
Hi, thanks for the syntax highlighting extension for riot!

I have one issue, which is perhaps easy to solve. Whenever opening a .tag file for the first time, it opens as Riot (Jade), but I would like it to open as Riot Tag. Is there any way I can configure this default?

Manne

**Comment by crisward** [comment]
I've done this same plugin for visual studio code, and it does the opposite. I thought sublime defaulted to that last one you used. Thanks for pointing this out. I was considering separating out the two plugins, one for jade and one for html, but if you use both this wouldn't solve the problem... 

If you have any suggestions, I'll be happy to consider them.

**Comment by crisward** [comment]
You can do this

![syntax-default](https://cloud.githubusercontent.com/assets/3109157/13219621/26182aae-d969-11e5-8d5b-5c52b4f64f25.png)

**Comment by crisward** [comment]
I'll close this issue, as it's nothing to do with the syntax file.
