### ISSUE TITLE
stylus tag compiling issue.

### ISSUE THREAD

**Issue by lijujose-daffodil** [crisward/sublime-tag#5]
Hi,

In order to highlight stylus tag in .tag files, I am using style(type="text/stylus"). I got the proper stylus highlighting , but it throws error while compiling this .tag file into .ja using Gulp-riot.

Just want to know, am I using the right syntax i.e. style(type="text/stylus"). for highlighting stylus tag or  is it something else?

Please help.

**Comment by crisward** [comment]
Yes, I use text/stylus. The Riot compiler removes the word text from the type attribute, so it just left with stylus, so it would work with and without. (https://github.com/riot/compiler/blob/master/dist/riot.compiler.js#L481)

Do you need to specify the pre-processor in gulp-riot options? Also make sure you have stylus installed. Finally, perhaps try just using `type="stylus"` if that works let me know and I can change the syntax highlight to accept that as an option.

**Comment by crisward** [comment]
jade syntax now accepts - v 0.1.7

`style(type="stylus").` as well as `style(type="text/stylus").`
