### ISSUE TITLE
Incorrect highlighting for attributes names with underscore

### ISSUE THREAD

**Issue by pkorzeniewski** [crisward/sublime-tag#6]
Given a `my_attribute` attribute name, the `_attribute` part is highlighted in different color than the `my`

**Comment by crisward** [comment]
Underscores are fairly uncommon in attribute names, riot I think favours dashes which it converts to camelCase. 

I'll take a look and see what I can do.

**Comment by crisward** [comment]
as of release 1.10 now allowed underscores in attribute names for both jade and html highlighters
