### ISSUE TITLE
Sublime Text 3 3113 compatibility

### ISSUE THREAD

**Issue by moritzschepp** [crisward/sublime-tag#7]
Hey,

to start: great package, it helps me a lot every day! Thanks a lot!

Perhaps you could have a look at this thread:
https://forum.sublimetext.com/t/syntax-highlighting-problem-with-3113-apparent-recursion-within-a-with-prototype-action-25000-context-sanity-limit-hit/19914/19

I have that exact problem when I install "Riot Tag" within ST 3113. The error popped up immediately after the upgrade to 3113. In my case, I'm seeing this:

![screenshot from 2016-05-13 12 39 40](https://cloud.githubusercontent.com/assets/506366/15245589/cf4cd880-1907-11e6-9f8b-9c4bac43d884.png)

Or is this a ST issue? I have no specific ruby packages installed ... the ruby syntax file the message mentions is built in.

**Comment by uxmoon** [comment]
+1 Here at work we are developing using riotJS and using the riot tag package. After the ST new update we receive the same error message.

**Comment by crisward** [comment]
I think sublime has messed with their regex stuff. I'll take a look over the weekend.

**Comment by uxmoon** [comment]
@crisward cool, thanks.

**Comment by crisward** [comment]
Just looking at this - https://forum.sublimetext.com/t/syntax-highlighting-problem-with-3113-apparent-recursion-within-a-with-prototype-action-25000-context-sanity-limit-hit/19914/21 

It looks like it effecting lots of community syntax highlighters. It's not clear from that what I can do to alleviate this issue. The same `. tmLanguage` file is used in my vscode version of this and it's working fine. https://github.com/crisward/riot-tag

Hopefully sublime will release a patch soon, or at least suggestions to package authors.

**Comment by crisward** [comment]
Fixed. (1.0.9)

The bug was caused by a circular dependency between highlighters within the html highlighter. I removed this and references to php,python and ruby which I don't think were really necessary anyway.

**Comment by moritzschepp** [comment]
Nice, thanks a lot!
